# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
#     This is for yarn installation
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
        
    - name: Build React App
      run: yarn build
      
    - name: creating axios package
    - run : yarn add axios 
      
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./build GitHubFinder.surge.sh --token ${{ secrets.Surge_Token }}
